"""add: indexes

Revision ID: 09e5d80a53a4
Revises: 50abfd8c31de
Create Date: 2023-04-27 20:56:16.600304

"""
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "09e5d80a53a4"
down_revision = "50abfd8c31de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("casts", "hash", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column("casts", "thread_hash", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column("casts", "text", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column("casts", "timestamp", existing_type=mysql.BIGINT(), nullable=False)
    op.alter_column("casts", "author_fid", existing_type=mysql.BIGINT(), nullable=False)
    op.create_index("ix_casts_author_fid", "casts", ["author_fid"], unique=False)
    op.create_index(
        "ix_casts_thread_hash", "casts", ["thread_hash"], unique=False, mysql_length=63
    )
    op.create_index("ix_casts_timestamp", "casts", ["timestamp"], unique=False)
    op.alter_column("locations", "id", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column(
        "locations", "description", existing_type=mysql.TEXT(), nullable=False
    )
    op.alter_column("reactions", "hash", existing_type=mysql.TEXT(), nullable=False)
    op.create_index(
        "ix_reactions_author_fid", "reactions", ["author_fid"], unique=False
    )
    op.create_index(
        "ix_reactions_target_hash",
        "reactions",
        ["target_hash"],
        unique=False,
        mysql_length=63,
    )
    op.create_index("ix_reactions_timestamp", "reactions", ["timestamp"], unique=False)
    op.alter_column(
        "users",
        "fid",
        existing_type=mysql.BIGINT(),
        nullable=False,
        autoincrement=False,
    )
    op.alter_column("users", "display_name", existing_type=mysql.TEXT(), nullable=False)
    op.alter_column(
        "users", "following_count", existing_type=mysql.BIGINT(), nullable=False
    )
    op.alter_column(
        "users", "follower_count", existing_type=mysql.BIGINT(), nullable=False
    )
    op.alter_column("users", "verified", existing_type=mysql.BIGINT(), nullable=False)
    op.alter_column(
        "users",
        "generated_farcaster_address",
        existing_type=mysql.TEXT(),
        nullable=False,
    )
    op.create_index(
        "ix_users_address", "users", ["address"], unique=False, mysql_length=63
    )
    op.create_index(
        "ix_users_username", "users", ["username"], unique=False, mysql_length=63
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="users", mysql_length=63)
    op.drop_index("ix_users_address", table_name="users", mysql_length=63)
    op.alter_column(
        "users",
        "generated_farcaster_address",
        existing_type=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column("users", "verified", existing_type=mysql.BIGINT(), nullable=True)
    op.alter_column(
        "users", "follower_count", existing_type=mysql.BIGINT(), nullable=True
    )
    op.alter_column(
        "users", "following_count", existing_type=mysql.BIGINT(), nullable=True
    )
    op.alter_column("users", "display_name", existing_type=mysql.TEXT(), nullable=True)
    op.alter_column(
        "users", "fid", existing_type=mysql.BIGINT(), nullable=True, autoincrement=False
    )
    op.drop_index("ix_reactions_timestamp", table_name="reactions")
    op.drop_index("ix_reactions_target_hash", table_name="reactions", mysql_length=63)
    op.drop_index("ix_reactions_author_fid", table_name="reactions")
    op.alter_column("reactions", "hash", existing_type=mysql.TEXT(), nullable=True)
    op.alter_column(
        "locations", "description", existing_type=mysql.TEXT(), nullable=True
    )
    op.alter_column("locations", "id", existing_type=mysql.TEXT(), nullable=True)
    op.drop_index("ix_casts_timestamp", table_name="casts")
    op.drop_index("ix_casts_thread_hash", table_name="casts", mysql_length=63)
    op.drop_index("ix_casts_author_fid", table_name="casts")
    op.alter_column("casts", "author_fid", existing_type=mysql.BIGINT(), nullable=True)
    op.alter_column("casts", "timestamp", existing_type=mysql.BIGINT(), nullable=True)
    op.alter_column("casts", "text", existing_type=mysql.TEXT(), nullable=True)
    op.alter_column("casts", "thread_hash", existing_type=mysql.TEXT(), nullable=True)
    op.alter_column("casts", "hash", existing_type=mysql.TEXT(), nullable=True)
    # ### end Alembic commands ###
