"""add: eth_transactions table

Revision ID: 1b118acbdc6d
Revises: e606b572cdb4
Create Date: 2023-03-09 14:31:51.079577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b118acbdc6d'
down_revision = 'e606b572cdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('address_fid', sa.BigInteger(), nullable=False),
    sa.Column('address_external', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('block_num', sa.BigInteger(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('erc721_token_id', sa.String(), nullable=True),
    sa.Column('erc1155_metadata', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_external'], ['users.external_address'], ),
    sa.ForeignKeyConstraint(['address_fid'], ['users.fid'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eth_transactions')
    # ### end Alembic commands ###
