"""update: remove ens data from users

Revision ID: 1efd2fed00e2
Revises: e9c860dbcb54
Create Date: 2023-03-13 11:03:11.324877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1efd2fed00e2'
down_revision = 'e9c860dbcb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'discord')
    op.drop_column('users', 'email')
    op.drop_column('users', 'telegram')
    op.drop_column('users', 'github')
    op.drop_column('users', 'ens')
    op.drop_column('users', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('ens', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('github', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram', mysql.VARCHAR(length=63), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('discord', mysql.VARCHAR(length=63), nullable=True))
    op.add_column('users', sa.Column('twitter', mysql.VARCHAR(length=63), nullable=True))
    # ### end Alembic commands ###
