"""add: init

Revision ID: 4dc8bc5ebea1
Revises: 
Create Date: 2023-03-11 17:06:48.911660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc8bc5ebea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('users',
    sa.Column('fid', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('pfp_url', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.BigInteger(), nullable=True),
    sa.Column('bio_text', sa.String(length=255), nullable=True),
    sa.Column('location_place_id', sa.String(length=255), nullable=True),
    sa.Column('farcaster_address', sa.String(length=63), nullable=True),
    sa.Column('external_address', sa.String(length=63), nullable=True),
    sa.Column('registered_at', sa.BigInteger(), nullable=True),
    sa.Column('ens', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=63), nullable=True),
    sa.Column('telegram', sa.String(length=63), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('discord', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
