"""add: initial models

Revision ID: 50abfd8c31de
Revises: 
Create Date: 2023-04-27 20:38:07.605784

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "50abfd8c31de"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casts",
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.Column("thread_hash", sa.String(length=255), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("author_fid", sa.Integer(), nullable=False),
        sa.Column("parent_hash", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.String(length=63), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reactions",
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.Column("reaction_type", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("target_hash", sa.String(length=255), nullable=True),
        sa.Column("author_fid", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "users",
        sa.Column("fid", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=63), nullable=True),
        sa.Column("display_name", sa.String(length=127), nullable=False),
        sa.Column("pfp_url", sa.String(length=255), nullable=True),
        sa.Column("bio_text", sa.String(length=255), nullable=True),
        sa.Column("following_count", sa.Integer(), nullable=False),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("generated_farcaster_address", sa.String(length=63), nullable=False),
        sa.Column("address", sa.String(length=63), nullable=True),
        sa.Column("registered_at", sa.BigInteger(), nullable=True),
        sa.Column("location_id", sa.String(length=63), nullable=True),
        sa.PrimaryKeyConstraint("fid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("reactions")
    op.drop_table("locations")
    op.drop_table("casts")
    # ### end Alembic commands ###
