"""add: cast table

Revision ID: 6144d0083250
Revises: 1efd2fed00e2
Create Date: 2023-03-14 16:08:37.297569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6144d0083250'
down_revision = '1efd2fed00e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casts',
    sa.Column('hash', sa.String(length=127), nullable=False),
    sa.Column('thread_hash', sa.String(length=127), nullable=False),
    sa.Column('parent_hash', sa.String(length=127), nullable=True),
    sa.Column('text', sa.String(length=511), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('author_fid', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casts')
    # ### end Alembic commands ###
