"""initial migration

Revision ID: 89bfcf99a11a
Revises: 
Create Date: 2023-03-29 17:30:55.035441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bfcf99a11a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casts',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('thread_hash', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('author_fid', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_hash'], ['casts.hash'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('external_addresses',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('ens', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('bio_text', sa.String(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Integer(), nullable=False),
    sa.Column('farcaster_address', sa.String(), nullable=False),
    sa.Column('external_address', sa.String(), nullable=True),
    sa.Column('registered_at', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['external_address'], ['external_addresses.address'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('eth_transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('address_fid', sa.Integer(), nullable=False),
    sa.Column('address_external', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('block_num', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('erc721_token_id', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address_external'], ['external_addresses.address'], ),
    sa.ForeignKeyConstraint(['address_fid'], ['users.fid'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('erc1155_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eth_transaction_hash', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eth_transaction_hash'], ['eth_transactions.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erc1155_metadata')
    op.drop_table('eth_transactions')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('external_addresses')
    op.drop_table('casts')
    # ### end Alembic commands ###
