"""update: verified from int to boolean

Revision ID: ab09f6a8ec6e
Revises: 4dc8bc5ebea1
Create Date: 2023-03-12 20:26:06.610482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab09f6a8ec6e'
down_revision = '4dc8bc5ebea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
