"""add: erc1155_metadata table

Revision ID: bf8c3041d1aa
Revises: ccdab7655ba8
Create Date: 2023-03-15 15:12:46.632090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf8c3041d1aa'
down_revision = 'ccdab7655ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erc1155_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eth_transaction_hash', sa.String(length=127), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('eth_transactions', 'erc1155_metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_transactions', sa.Column('erc1155_metadata', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('erc1155_metadata')
    # ### end Alembic commands ###
