"""add: eth_transactions table

Revision ID: ccdab7655ba8
Revises: 6144d0083250
Create Date: 2023-03-15 14:06:43.412384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdab7655ba8'
down_revision = '6144d0083250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_transactions',
    sa.Column('hash', sa.String(length=127), nullable=False),
    sa.Column('address_fid', sa.BigInteger(), nullable=False),
    sa.Column('address_external', sa.String(length=63), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('block_num', sa.BigInteger(), nullable=True),
    sa.Column('from_address', sa.String(length=63), nullable=True),
    sa.Column('to_address', sa.String(length=63), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('erc721_token_id', sa.String(length=127), nullable=True),
    sa.Column('erc1155_metadata', sa.String(length=255), nullable=True),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('asset', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eth_transactions')
    # ### end Alembic commands ###
