"""init: create schema

Revision ID: e606b572cdb4
Revises: 
Create Date: 2023-03-09 09:58:59.645312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e606b572cdb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('users',
    sa.Column('fid', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.BigInteger(), nullable=True),
    sa.Column('bio_text', sa.String(), nullable=True),
    sa.Column('location_place_id', sa.String(), nullable=True),
    sa.Column('farcaster_address', sa.String(), nullable=True),
    sa.Column('external_address', sa.String(), nullable=True),
    sa.Column('registered_at', sa.BigInteger(), nullable=True),
    sa.Column('ens', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_place_id'], ['locations.place_id'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('casts',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('thread_hash', sa.String(), nullable=True),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('author_fid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author_fid'], ['users.fid'], ),
    sa.ForeignKeyConstraint(['parent_hash'], ['casts.hash'], ),
    sa.ForeignKeyConstraint(['thread_hash'], ['casts.hash'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('parent_association',
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('cast_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cast_hash'], ['casts.hash'], ),
    sa.ForeignKeyConstraint(['parent_hash'], ['casts.hash'], )
    )
    op.create_table('reactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('target_hash', sa.String(), nullable=True),
    sa.Column('author_fid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author_fid'], ['users.fid'], ),
    sa.ForeignKeyConstraint(['target_hash'], ['casts.hash'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('parent_association')
    op.drop_table('casts')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
