"""update: separate external address into its own table

Revision ID: e9c860dbcb54
Revises: ab09f6a8ec6e
Create Date: 2023-03-13 09:34:06.662768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c860dbcb54'
down_revision = 'ab09f6a8ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_addresses',
    sa.Column('address', sa.String(length=63), nullable=False),
    sa.Column('ens', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=63), nullable=True),
    sa.Column('telegram', sa.String(length=63), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('discord', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_addresses')
    # ### end Alembic commands ###
