###
http://localhost:8000/

### 
POST http://localhost:8000/query HTTP/1.1
content-type: application/json

{
    "type": "english-advanced",
    "query": "get users who like the most liked cast, but only return the user with username that starts with 'b', limit 10"
}


### 
POST http://localhost:8000/query HTTP/1.1
content-type: application/json

{
    "type": "raw",
    "query": "SQL: WITH most_liked_cast AS (SELECT target_hash, COUNT(*) AS like_count FROM reactions WHERE reaction_type = 'like' GROUP BY target_hash ORDER BY like_count DESC LIMIT 1), b_users AS (SELECT users.* FROM users, reactions, most_liked_cast WHERE users.username LIKE 'd%' AND users.fid = reactions.author_fid AND reactions.target_hash = most_liked_cast.target_hash AND reactions.reaction_type = 'like' ORDER BY RAND() LIMIT 3) SELECT * FROM b_users;"
}

### 
POST http://localhost:8000/query HTTP/1.1
content-type: application/json

{
    "type": "english",
    "query": "delete one random user"
}

### 
POST http://localhost:8000/translate HTTP/1.1
content-type: application/json

{
    "type": "english-advanced",
    "query": "get one random cast"
}